# Generated by Django 5.0.2 on 2025-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Тело Ззапроса')),
                ('request_url', models.TextField(verbose_name='URL')),
                ('request_method', models.CharField(max_length=32, verbose_name='Метод запроса')),
                ('request_headers', models.JSONField(blank=True, null=True, verbose_name='Заголовки запроса')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Тело ответа')),
                ('response_status_code', models.IntegerField(null=True, verbose_name='Статус ответа')),
                ('response_headers', models.JSONField(blank=True, null=True, verbose_name='Заголовки ответа')),
                ('request_timestamp', models.DateTimeField(verbose_name='Время запроса')),
                ('response_timestamp', models.DateTimeField(verbose_name='Время ответа')),
                ('message', models.TextField(blank=True, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Лог внешнего запроса',
                'verbose_name_plural': 'Логи внешних запросов',
            },
        ),
    ]
