# Generated by Django 5.0.2 on 2025-08-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="request_query_params",
            field=models.JSONField(blank=True, null=True, verbose_name="Параметры запроса"),
        ),
    ]
