# Generated by Django 5.0.2 on 2025-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_request', '0002_requestlog_request_query_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='request_timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Время запроса'),
        ),
    ]
